FROM microsoft/dotnet:2.1-sdk as build-env
WORKDIR /app

COPY GrainInterfaces ./GrainInterfaces
COPY WebServer ./WebServer

WORKDIR /app/WebServer

RUN dotnet restore
RUN dotnet publish -c Release -o out

FROM microsoft/dotnet:2.1-aspnetcore-runtime-alpine
WORKDIR /app
COPY --from=build-env /app/WebServer/out .

EXPOSE 80/tcp

ENTRYPOINT ["dotnet", "WebServer.dll"]